apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc-db
spec:
  accessModes:
    - ReadWriteMany # this means that many pods can read and write to this storage class. Other possibilities are:
    # - ReadWriteOne
    # - ReadOnly etc.
  resources:
    requests:
      storage: 1Gi
  storageClassName: "demo-storage" # this is the storage class name defined in storage-class.yaml