apiVersion: v1
kind: Pod
metadata:
  name: "myapp-multicontainer-pod"
  namespace: default
  labels:
    app: "myapp-multicontainer-pod"
spec:
  containers:
  - name: first-container
    image: "debian-slim:latest"
    ports:
    - containerPort:  80
      name:  http
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
  - name: second-container
    image: nginx
    ports:
    - containerPort: 81
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
  